theme: jekyll-theme-slate

- ğŸ‘‹ Hi, Iâ€™m Bernard McNamee @bjmcnamee<br>
- ğŸ‘€ Iâ€™m interested in all things related to Technical Data Analysis<br>
- ğŸ’ï¸ I love to crunch data - Iâ€™m working as a Technical Data Analyst with a research charity, Heartbeat Trust<br>
- ğŸŒ± In final year of Data Science & Analytics at MTU evening studies<br>
- ğŸ“« How to reach me : bernardmcnamee@gmail.com<br>
